jwt.secret=8xtOlOopfQzGZniJOLdDV6FdFsa8TFTG0WTDUuCdrmcpElTEEM6SNYmQ6gO5dH0rpefkWS1OtR7SSHb7by3eQ==b
jwt.expiration_ms=3600000

spring.security.oauth2.client.registration.kakao.redirect-uri=http://localhost:8080
spring.security.oauth2.client.provider.kakao.token-uri=https://kauth.kakao.com/oauth/token
